config/routes.rb
Rails.application.routes.draw do


  resources :rtc_sessions
  resources :authorizations_e911_contexts
  resources :e911_contexts
  resources :authorizations
  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users

  get    '/pages/main'                 => 'pages#main'
  get    '/pages/authorize'            => 'pages#authorize'
  get    '/oauth/callback'             => 'authorizations#callback'


end

app/models/rtc_session.rb
class RTCSession < ActiveRecord::Base
  include BelongsToUser

  belongs_to :user

  before_create :start_session


  def start_session
    resp = start_response
    p resp
  end
  
  def start_url
    "#{cfg.fqdn}#{start_path}"
  end

  def start_session_data
    {
      mediaType: "dtls-srtp",
      ice:  "true",
      services: [
                 "ip_voice_call",
                 "ip_video_call"
                ]
    }
  end

  def start_data
    {
      session: start_session_data
    }
  end

  def start_body
    start_data.to_json
  end


  def start_path
#var GW_URL = "https://api.att.com",SERVICE_NAME="RTC",version="v1", REGISTER_RESOURCE = "sessions";
#var registerURL = GW_URL + "/" + SERVICE_NAME + "/" + version + "/" + REGISTER_RESOURCE;

    "/RTC/v1/sessions"
  end

  def cfg
    @cfg ||= Settings.auth_att
  end

  def access_token
    authorization.try(:access_token)
  end

  def authorization
    user.authorizations.authorized.first
  end

  def e911id
    authorization.try(:e911id)
  end

  def start_response
    RestClient.reset_before_execution_procs
    RestClient.add_before_execution_proc do |req, params|
      req['Authorization'] = "Bearer #{access_token}"
      req["x-e911id"] = self.e911id
    end

    begin
      RestClient.post(start_url, 
                      start_body, 
                      content_type: 'application/json', 
                      accept: 'application/json',
                      #authorization: "Bearer #{access_token}"
                      )
    rescue => e
      Rails.logger.error("**ERROR** #{e}")
      raise
    end
  end

end

		# req.open("POST", registerURL, true);
		# req.setRequestHeader("content-type", "application/json");
		# req.setRequestHeader("accept", "application/json");
		# req.setRequestHeader("x-e911id", xE911Id);
		# req.setRequestHeader("authorization", "Bearer " + accessToken);

#var GW_URL = "https://api.att.com",SERVICE_NAME="RTC",version="v1", REGISTER_RESOURCE = "sessions";
#var registerURL = GW_URL + "/" + SERVICE_NAME + "/" + version + "/" + REGISTER_RESOURCE;

app/controllers/rtc_sessions_controller.rb
class RTCSessionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_rtc_session, only: [:show, :edit, :update, :destroy]

  # GET /rtc_sessions
  # GET /rtc_sessions.json
  def index
    @rtc_sessions = RTCSession.all
  end

  # GET /rtc_sessions/1
  # GET /rtc_sessions/1.json
  def show
  end

  # GET /rtc_sessions/new
  def new
    @rtc_session = RTCSession.new
  end

  # GET /rtc_sessions/1/edit
  def edit
  end

  # POST /rtc_sessions
  # POST /rtc_sessions.json
  def create
    @rtc_session = RTCSession.new(rtc_session_params)

    respond_to do |format|
      if @rtc_session.save
        format.html { redirect_to @rtc_session, notice: 'RTC session was successfully created.' }
        format.json { render :show, status: :created, location: @rtc_session }
      else
        format.html { render :new }
        format.json { render json: @rtc_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rtc_sessions/1
  # PATCH/PUT /rtc_sessions/1.json
  def update
    respond_to do |format|
      if @rtc_session.update(rtc_session_params)
        format.html { redirect_to @rtc_session, notice: 'RTC session was successfully updated.' }
        format.json { render :show, status: :ok, location: @rtc_session }
      else
        format.html { render :edit }
        format.json { render json: @rtc_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rtc_sessions/1
  # DELETE /rtc_sessions/1.json
  def destroy
    @rtc_session.destroy
    respond_to do |format|
      format.html { redirect_to rtc_sessions_url, notice: 'RTC session was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rtc_session
      @rtc_session = RTCSession.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rtc_session_params
      params.require(:rtc_session).permit(:user_id, :sessionId, :started_at)
    end
end

app/helpers/rtc_sessions_helper.rb
module RTCSessionsHelper
end
RtcSessionsHelper = RTCSessionsHelper

app/views/rtc_sessions/_form.html.haml
= simple_form_for(@rtc_session) do |f|
  = f.error_notification

  .form-inputs
    = f.association :user
    = f.input :sessionId
    = f.input :started_at

  .form-actions
    = f.button :submit

app/views/rtc_sessions/edit.html.haml
%h1 Editing rtc_session

= render 'form'

= link_to 'Show', @rtc_session
\|
= link_to 'Back', rtc_sessions_path

app/views/rtc_sessions/index.html.haml
%h1 Listing rtc_sessions

%table
  %thead
    %tr
      %th User
      %th Sessionid
      %th Started at
      %th
      %th
      %th

  %tbody
    - @rtc_sessions.each do |rtc_session|
      %tr
        %td= rtc_session.user
        %td= rtc_session.sessionId
        %td= rtc_session.started_at
        %td= link_to 'Show', rtc_session
        %td= link_to 'Edit', edit_rtc_session_path(rtc_session)
        %td= link_to 'Destroy', rtc_session, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New RTC session', new_rtc_session_path

app/views/rtc_sessions/new.html.haml
%h1 New rtc_session

= render 'form'

= link_to 'Back', rtc_sessions_path

app/views/rtc_sessions/show.html.haml
%p#notice= notice

%p
  %b User:
  = @rtc_session.user
%p
  %b Sessionid:
  = @rtc_session.sessionId
%p
  %b Started at:
  = @rtc_session.started_at

= link_to 'Edit', edit_rtc_session_path(@rtc_session)
\|
= link_to 'Back', rtc_sessions_path