config/routes.rb
Rails.application.routes.draw do


  resources :rtc_sessions
  resources :authorizations_e911_contexts
  resources :e911_contexts
  resources :authorizations
  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users

  get    '/pages/main'                 => 'pages#main'
  get    '/pages/authorize'            => 'pages#authorize'
  get    '/oauth/callback'             => 'authorizations#callback'


end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  include BelongsToUser

  has_many :authorizations_e911_contexts, :dependent => :destroy
  has_many :e911_contexts, :through => :authorizations_e911_contexts

  scope :authorized, -> { where("authorizations.access_token IS NOT NULL") }

  def auth_url
    "#{cfg.fqdn}#{auth_path}?" + URI.encode_www_form(auth_params)
  end

  def authorized?
    access_token.present?
  end

  def e911id
    e911_contexts.first.try(:e911id)
  end

  def has_e911id?
    e911id.present?
  end

  def exchange_code
    content_type = 'application/x-www-form-urlencoded'
    puts "URL: #{token_url} PARAMS=#{token_params}"
    json_ans = RestClient.post(token_url, token_params, content_type: content_type, accept: 'application/json')
    ans = JSON.parse(json_ans)
    puts "ANS=#{ans}"
    access_token, refresh_token = ans['access_token'], ans['refresh_token']
    self.update_attributes(access_token: access_token, refresh_token: refresh_token, expires_in: ans['expires_in'])
  end


  private 

  def auth_header
    { "Authorization" => "Bearer #{access_token}"}
  end


  def auth_params
    {
      #scope: cfg.scope,
      scope: "WEBRTCMOBILE,EMERGENCYSERVICES",
      response_type: 'code',
      client_id: cfg.client_id,
      redirect_uri: cfg.redirect_uri,
      state: self.id.to_s
    }.with_indifferent_access
  end

  def token_params
    {
      client_id: cfg.client_id,
      client_secret: cfg.client_secret,
      grant_type: 'authorization_code',
      redirect_uri: cfg.redirect_uri,
      code: self.auth_code,
    }
  end

  def token_url 
    "#{cfg.fqdn}#{token_path}"
  end

  def auth_path
    "/oauth/v4/authorize"
  end

  def token_path
    "/oauth/token"
  end

  def cfg
    @cfg ||= Settings.auth_att
  end

end

app/controllers/authorizations_controller.rb
class AuthorizationsController < ApplicationController
  before_action :authenticate_user!, except: [:callback]

  before_action :set_authorization, only: [:show, :edit, :update, :destroy]

  def callback
    id = params[:state].to_i
    auth_code = params[:code]

    auth = Authorization.where(id: id).first
    if auth
      auth.update_attributes(auth_code: auth_code)
      auth.exchange_code
    end
    redirect_to pages_main_path
    #head :ok
  end



  # GET /authorizations/1/edit
  def edit
    id = params[:id].to_i
    @contexts = E911Context.for_user(current_user)
    @authorization = Authorization.where(id: id).first
  end

  # PATCH/PUT /authorizations/1
  # PATCH/PUT /authorizations/1.json
  def update
    p "UPDATE PARAMS: #{params}"

  end

  # GET /authorizations
  # GET /authorizations.json
  def index
    @authorizations = Authorization.all
  end

  # GET /authorizations/1
  # GET /authorizations/1.json
  def show
  end

  # GET /authorizations/new
  def new
    @authorization = Authorization.new(user: current_user)
  end


  # POST /authorizations
  # POST /authorizations.json
  def create
    @authorization = Authorization.new(authorization_params)

    respond_to do |format|
      if @authorization.save
        format.html { redirect_to @authorization, notice: 'Authorization was successfully created.' }
        format.json { render :show, status: :created, location: @authorization }
      else
        format.html { render :new }
        format.json { render json: @authorization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authorizations/1
  # DELETE /authorizations/1.json
  def destroy
    @authorization.destroy
    respond_to do |format|
      format.html { redirect_to authorizations_url, notice: 'Authorization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_authorization
      @authorization = Authorization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def authorization_params
      params.require(:authorization).permit(:references, :carrier, :access_token, :refresh_token, :authorized_at, :e911id)
    end
end

app/helpers/authorizations_helper.rb
module AuthorizationsHelper
end

app/views/authorizations/_edit.html.haml
= form_tag do
  - @contexts.each do |ctx|
    = radio_button_tag(:ctx, ctx.id.to_s)
    = label_tag("ctx_#{ctx.id}".to_sym, "#{ctx.houseNumber} #{ctx.street} #{ctx.city} #{ctx.state} #{ctx.zip}")
  = submit_tag("Use selected E911 Context")

  

app/views/authorizations/_form.html.haml
= simple_form_for(@authorization) do |f|
  = f.error_notification

  .form-inputs
    = f.input :user
    = f.input :carrier
    = f.input :access_token
    = f.input :refresh_token
    = f.input :expires_in

  .form-actions
    = f.button :submit

app/views/authorizations/edit.html.haml
%h1 Set E911

- @contexts.each do |ctx|
  %div.radio
    %label
      %input{type: 'radio', name: 'authContext', value: ctx.id.to_s, id: "context-#{ctx.id}"}
        = "#{ctx.houseNumber} #{ctx.street} #{ctx.city} #{ctx.state} #{ctx.zip}"

%button.btn.btn-primary{type: "submit"} Use selected E911 Context
  

app/views/authorizations/index.html.haml
%h1 Listing authorizations

%table
  %thead
    %tr
      %th References
      %th Carrier
      %th Access token
      %th Refresh token
      %th Authorized at
      %th E911id
      %th
      %th
      %th

  %tbody
    - @authorizations.each do |authorization|
      %tr
        %td= authorization.references
        %td= authorization.carrier
        %td= authorization.access_token
        %td= authorization.refresh_token
        %td= authorization.authorized_at
        %td= authorization.e911id
        %td= link_to 'Show', authorization
        %td= link_to 'Edit', edit_authorization_path(authorization)
        %td= link_to 'Destroy', authorization, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Authorization', new_authorization_path

app/views/authorizations/new.html.haml
%h1 New authorization

= render 'form'

= link_to 'Back', authorizations_path

app/views/authorizations/show.html.haml
%p#notice= notice

%p
  %b References:
  = @authorization.references
%p
  %b Carrier:
  = @authorization.carrier
%p
  %b Access token:
  = @authorization.access_token
%p
  %b Refresh token:
  = @authorization.refresh_token
%p
  %b Authorized at:
  = @authorization.authorized_at
%p
  %b E911id:
  = @authorization.e911id

= link_to 'Edit', edit_authorization_path(@authorization)
\|
= link_to 'Back', authorizations_path